#!/bin/sh

STARTTIME=$(date +%s%3N)
while : ; do
	ELAPSED=$(($(date +%s%3N) - $STARTTIME))
	printf "\r%02d:%02d:%02d" "$(((ELAPSED / (1000*60*60)) % 24))" "$(((ELAPSED / (1000*60))  % 60))" "$(((ELAPSED / 1000) % 60))"
	sleep 1
done

