#!/bin/sh

case "$(printf "Shutdown\nReboot\nSuspend" | dmenu -i)" in
	"Shutdown") dconfirm "Are you sure you want to shutdown?" poweroff ;;
	"Reboot") dconfirm "Are you sure you want to reboot?" reboot ;;
	"Suspend") "$(slock $(sleep 1 && echo mem > /sys/power/state))" ;;
esac

