#!/bin/sh

ITEMS="\
🎧 $(mpctl current)
⌨ $(sed -nE 's/(^.*XkbLayout.*")(.*)(")/\2/p' /etc/X11/xorg.conf.d/00-keyboard.conf | tr ',' '\n' | head -n $(($(xset -q | sed -nE 's/(^.*LED.*)([0-9]{3})([0-9]{1})([0-9]{3})/\3/p')+1)) | tail -1)
🔋 $(cat /sys/class/power_supply/BAT[0-9]/capacity)%
🔊 $(pactl list sinks | grep -oEm1 '[0-9]+%' | head -1)
🌐 $(ip r g 1 | grep -Eo '[0-9\.]+{7}' | tail -1)
$(date +"📅 %d-%m-%Y%n⌚ %H:%M")
"

case "$(echo "$ITEMS" | grep -n "$(echo "$ITEMS"| dmenu -i)" | cut -d: -f1)" in
	4) st -e pulsemixer & ;;
	6) st -e calcurse & ;;
esac

